version: '3.8'

services:
  anomaly-detector:
    build: .
    ports:
      - "5000:80"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-your_influxdb_token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-your_org}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-iot_data}
    depends_on:
      - influxdb
    restart: unless-stopped
    volumes:
      - ./data:/app/data

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=iot_org
      - DOCKER_INFLUXDB_INIT_BUCKET=iot_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=your_influxdb_token
    volumes:
      - influxdb-data:/var/lib/influxdb2

volumes:
  influxdb-data:
